Script started on 2015年03月10日 (週二) 20時41分05秒
]0;F74032023@2015cpp: ~/lab1F74032023@2015cpp:~/lab1$ git help git config[9P--helpconfig -l[2Pwhoami; pwdgit config -l‐l --global user.email "F74032023@mail.ncku.eduu.tw"[A]0;F74032023@2015cpp: ~/lab1F74032023@2015cpp:~/lab1$ [C[C[C[C[C[C[C[C[C[C ‐l[K
[K[A[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C[C-l[2Pwhoami; pwdgit config -l[3P--helphelp git config[Kgit help git config[Kg+++[K -o A A.cpp
]0;F74032023@2015cpp: ~/lab1F74032023@2015cpp:~/lab1$ g++ -o A A.cpp[K[K[K[K[K[K[K[K[K[K[K[K[K[K./A
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;F74032023@2015cpp: ~/lab1F74032023@2015cpp:~/lab1$ exit

Script done on 2015年03月10日 (週二) 20時41分43秒
